export type SlideKind = "portada" | "texto" | "tabla" | "galeria" | "mockup" | "social" | "cierre";

export interface Slide {
  id: string;
  n: number;
  kind: SlideKind;
  title: string;
  section: "manual" | "social";
  speaker: 1 | 2;
  speakerName: string;
  timeRange: string;
  keyPoints: string[];
  body?: string;
  assets?: string[];
}

export const SLIDES: Slide[] = [
  // ==========================================
  // PARTE 1: MANUAL DE MARCA & IDENTIDAD VISUAL
  // Orador 1: Especialista en Branding (Min 0:00 - 5:00)
  // ==========================================
  {
    id: "portada",
    n: 1,
    kind: "portada",
    title: "ALPACLADD — Fábrica de Hilados",
    section: "manual",
    speaker: 1,
    speakerName: "Orador 1 (Branding)",
    timeRange: "0:00 - 0:25",
    keyPoints: [
      "Presentar el proyecto: Manual de Marca y Estrategia de Marketing B2B para ALPACLADD.",
      "Rubro: Fábrica de hilados industriales (algodón peinado, alpaca y lana).",
      "Concepto rector: Precisión textil e innovación en procesos industriales.",
    ],
  },
  {
    id: "intro",
    n: 2,
    kind: "texto",
    title: "Introducción y Contexto Industrial",
    section: "manual",
    speaker: 1,
    speakerName: "Orador 1 (Branding)",
    timeRange: "0:25 - 0:50",
    keyPoints: [
      "Planta industrial con maquinaria europea y purificadores ópticos en tiempo real.",
      "El mercado B2B exige cero paradas de máquina y regularidad absoluta de títulos.",
      "La identidad visual busca transmitir sobriedad, ingeniería y confianza operativa.",
    ],
  },
  {
    id: "concepto",
    n: 3,
    kind: "texto",
    title: "Concepto: Precisión que Transforma Fibras",
    section: "manual",
    speaker: 1,
    speakerName: "Orador 1 (Branding)",
    timeRange: "0:50 - 1:15",
    keyPoints: [
      "Explicar la transición física: de fibras dispersas a hilo continuo en torsión perfecta.",
      "Simulador interactivo de torsión por metro (TPM) demostrando el rigor técnico.",
      "Cada decisión gráfica está anclada a la geometría de la maquinaria textil.",
    ],
  },
  {
    id: "mision",
    n: 4,
    kind: "tabla",
    title: "Misión, Visión y Valores Corporativos",
    section: "manual",
    speaker: 1,
    speakerName: "Orador 1 (Branding)",
    timeRange: "1:15 - 1:40",
    keyPoints: [
      "Misión: Fabricar hilados premium con materias primas trazables y tecnología robótica.",
      "Visión: Ser la hilandería de referencia en América Latina hacia 2030.",
      "Valores: Precisión estructural, sustentabilidad ambiental y alianza estratégica B2B.",
    ],
  },
  {
    id: "logo",
    n: 5,
    kind: "mockup",
    title: "Imagotipo Principal y Arquitectura",
    section: "manual",
    speaker: 1,
    speakerName: "Orador 1 (Branding)",
    timeRange: "1:40 - 2:05",
    keyPoints: [
      "Imagotipo compuesto por isotipo geométrico + tipografía institucional ajustada.",
      "Estructura modular: versión horizontal principal, vertical y aplicaciones del isotipo.",
      "Kerning expandido para garantizar legibilidad a micro y macroescala.",
    ],
  },
  {
    id: "isotipo",
    n: 6,
    kind: "galeria",
    title: "Morfología del Isotipo: Cono + Hilo + A",
    section: "manual",
    speaker: 1,
    speakerName: "Orador 1 (Branding)",
    timeRange: "2:05 - 2:30",
    keyPoints: [
      "Elemento 1: El cono o soporte cilíndrico de la hilandería industrial.",
      "Elemento 2: El hilo en torsión continua aportando sinuosidad y dinamismo.",
      "Elemento 3: La letra 'A' inicial de ALPACLADD en ángulos de 60 grados.",
    ],
  },
  {
    id: "construccion",
    n: 7,
    kind: "galeria",
    title: "Proceso de Diseño: Bocetos → Retícula → Vector",
    section: "manual",
    speaker: 1,
    speakerName: "Orador 1 (Branding)",
    timeRange: "2:30 - 3:00",
    keyPoints: [
      "Paso 1: Bocetado a mano alzada explorando iniciales y husos textiles.",
      "Paso 2: Retícula técnica y construcción con arcos áureos tangenciales.",
      "Paso 3: Vectorización final y consolidación de pesos de línea.",
    ],
  },
  {
    id: "seguridad",
    n: 8,
    kind: "texto",
    title: "Área de Seguridad y Zona de Exclusión",
    section: "manual",
    speaker: 1,
    speakerName: "Orador 1 (Branding)",
    timeRange: "3:00 - 3:20",
    keyPoints: [
      "Definición de la unidad de medida modular X (altura del triángulo interno de la A).",
      "Zona de exclusión obligatoria de 1X en los 4 márgenes perimetrales.",
      "Garantiza que ningún texto o elemento gráfico invada el imagotipo.",
    ],
  },
  {
    id: "reduccion",
    n: 9,
    kind: "texto",
    title: "Reducciones Mínimas: Impresión y Digital",
    section: "manual",
    speaker: 1,
    speakerName: "Orador 1 (Branding)",
    timeRange: "3:20 - 3:45",
    keyPoints: [
      "Imagotipo completo: mínimo 25 mm de ancho en offset y 120 px en digital.",
      "Isotipo aislado: mínimo 8 mm en etiquetas cosidas y 32 px en favicons/apps.",
      "Evita el empastado de tintas en telares y pérdida de legibilidad.",
    ],
  },
  {
    id: "paleta",
    n: 10,
    kind: "tabla",
    title: "Paleta Cromática Oficial",
    section: "manual",
    speaker: 1,
    speakerName: "Orador 1 (Branding)",
    timeRange: "3:45 - 4:05",
    keyPoints: [
      "Navy Blue (#0D1D34) y Corporate Blue (#1D5A8F): Solidez y autoridad industrial.",
      "Sky Blue (#5FA8D3): Acento luminoso y representación de filamentos.",
      "Cool Gray (#666666) y Off-White (#F2F2F2): Claridad en datos técnicos.",
    ],
  },
  {
    id: "tipos",
    n: 11,
    kind: "texto",
    title: "Tipografía Institucional: Raleway",
    section: "manual",
    speaker: 1,
    speakerName: "Orador 1 (Branding)",
    timeRange: "4:05 - 4:25",
    keyPoints: [
      "Familia tipográfica Raleway: Sans-serif geométrica con gran neutralidad técnica.",
      "Jerarquía: Bold (700) para titulares y números de título; Regular (400) para párrafos.",
      "Excelente comportamiento en bobinas de hilo, remitos y entornos digitales.",
    ],
  },
  {
    id: "versiones",
    n: 12,
    kind: "galeria",
    title: "Presentación Versátil del Logotipo",
    section: "manual",
    speaker: 1,
    speakerName: "Orador 1 (Branding)",
    timeRange: "4:25 - 4:45",
    keyPoints: [
      "Versión en escala de grises para remitos y offset económico.",
      "Monocromática (B/N puro) para sellos y grabado láser sobre conos.",
      "Versión invertida sobre fondos oscuros y simulación de bordado textil.",
    ],
  },
  {
    id: "incorrectos",
    n: 13,
    kind: "galeria",
    title: "Pautas de Uso: Aplicaciones Incorrectas",
    section: "manual",
    speaker: 1,
    speakerName: "Orador 1 (Branding)",
    timeRange: "4:45 - 5:00",
    keyPoints: [
      "Prohibido deformar proporciones, rotar o aplicar sombras duras.",
      "Prohibido alterar la paleta cromática o desbalancear el isotipo respecto al texto.",
    ],
  },
  {
    id: "mockups",
    n: 14,
    kind: "galeria",
    title: "Mockups en Piezas Físicas Reales",
    section: "manual",
    speaker: 1,
    speakerName: "Orador 1 (Branding)",
    timeRange: "5:00 - 5:20",
    keyPoints: [
      "Fotografía y render de bobinas industriales con fajas institucionales.",
      "Bolsas kraft ecológicas para envío de muestras de 1kg a talleres.",
      "Papelería técnica con stamping y uniformes de operario con bordado oficial.",
    ],
  },

  // ==========================================
  // PARTE 2: ESTRATEGIA DE MARKETING & SOCIAL MEDIA
  // Orador 2: Senior Community Manager (Min 5:00 - 10:00)
  // ==========================================
  {
    id: "publico",
    n: 15,
    kind: "tabla",
    title: "Público Objetivo B2B y Buyer Personas",
    section: "social",
    speaker: 2,
    speakerName: "Orador 2 (CM & Marketing)",
    timeRange: "5:20 - 5:50",
    keyPoints: [
      "Segmento 1: Tejedurías Industriales (Director de Planta / Dolor: Paradas de telar).",
      "Segmento 2: Marcas de Moda Premium (Diseñador Jefe / Dolor: Pilling y tacto áspero).",
      "Segmento 3: Talleres de Confección (Jefe de Taller / Dolor: Variación de calibre).",
    ],
  },
  {
    id: "estrategia",
    n: 16,
    kind: "texto",
    title: "Objetivos de Marketing B2B (SMART)",
    section: "social",
    speaker: 2,
    speakerName: "Orador 2 (CM & Marketing)",
    timeRange: "5:50 - 6:20",
    keyPoints: [
      "Objetivo 1: 25% de share of voice en el rubro textil premium en 12 meses.",
      "Objetivo 2: +40% en nuevas cuentas B2B mediante el embudo de muestra gratis.",
      "Objetivo 3: 15 toneladas despachadas de la nueva línea sustentable ECO-SPUN.",
    ],
  },
  {
    id: "tono",
    n: 17,
    kind: "texto",
    title: "Personalidad de Marca y Tono de Voz",
    section: "social",
    speaker: 2,
    speakerName: "Orador 2 (CM & Marketing)",
    timeRange: "6:20 - 6:45",
    keyPoints: [
      "Voz técnica, didáctica y basada en datos comprobables de laboratorio.",
      "Somos exactos, pedagógicos y colaborativos; no pretenciosos ni líricos.",
      "Hablamos el idioma de ingenieros textiles y confeccionistas profesionales.",
    ],
  },
  {
    id: "pilares",
    n: 18,
    kind: "galeria",
    title: "Los 4 Pilares de Contenido Estratégico",
    section: "social",
    speaker: 2,
    speakerName: "Orador 2 (CM & Marketing)",
    timeRange: "6:45 - 7:15",
    keyPoints: [
      "Pilar 1 (Producto): Fichas técnicas, títulos (30/1, 24/2) y resistencia cN/tex.",
      "Pilar 2 (Proceso): Maquinaria Savio, purgado electrónico y laboratorio ISO.",
      "Pilar 3 (Personas): Cultura de planta, operarios calificados y seguridad.",
      "Pilar 4 (Conocimiento): Academia ALPACLADD y tips para tejedores.",
    ],
  },
  {
    id: "instagram",
    n: 19,
    kind: "social",
    title: "Perfil Optimizado @alpacladd.hilados",
    section: "social",
    speaker: 2,
    speakerName: "Orador 2 (CM & Marketing)",
    timeRange: "7:15 - 7:45",
    keyPoints: [
      "Biografía optimizada con propuesta de valor única y linktree con catálogo.",
      "Insignia de cuenta B2B verificada y avatar de alto contraste.",
      "Historias destacadas (La Planta, Productos, Procesos, Academia) organizadas.",
    ],
  },
  {
    id: "feed",
    n: 20,
    kind: "social",
    title: "Plan de Contenidos: Feed Estratégico (6 Posts)",
    section: "social",
    speaker: 2,
    speakerName: "Orador 2 (CM & Marketing)",
    timeRange: "7:45 - 8:30",
    keyPoints: [
      "Parrilla estética tipo damero alternando placas tipográficas y fichas de producto.",
      "Copys redactados con ganchos técnicos, desarrollo de valor y CTAs claros.",
      "Uso de hashtags B2B especializados (#HiladosB2B, #PrecisionTextil, #AlgodonPeinado).",
    ],
  },
  {
    id: "stories",
    n: 21,
    kind: "social",
    title: "Stories Interactivas: Encuesta y Quiz",
    section: "social",
    speaker: 2,
    speakerName: "Orador 2 (CM & Marketing)",
    timeRange: "8:30 - 9:00",
    keyPoints: [
      "Encuesta interactiva para relevar el dolor principal de los talleres.",
      "Trivia técnica / Quiz para educar sobre el purgado óptico de coneras.",
      "Incremento del engagement y captura de insights cualitativos de la audiencia.",
    ],
  },
  {
    id: "reels",
    n: 22,
    kind: "social",
    title: "Video Reels: Procesos y Laboratorio",
    section: "social",
    speaker: 2,
    speakerName: "Orador 2 (CM & Marketing)",
    timeRange: "9:00 - 9:30",
    keyPoints: [
      "Microvideos dinámicos de 15s mostrando la transformación del algodón.",
      "Demostración visual del sensor láser Savio y pruebas dinámicas de tensión.",
      "Formato de máximo alcance orgánico para atraer confeccionistas en Instagram.",
    ],
  },
  {
    id: "publicidad",
    n: 23,
    kind: "social",
    title: "Publicidad Digital y Paid Media B2B",
    section: "social",
    speaker: 2,
    speakerName: "Orador 2 (CM & Marketing)",
    timeRange: "9:30 - 9:50",
    keyPoints: [
      "Embudo de 3 etapas en Meta Ads y LinkedIn: Muestras (TOFU), Tecnología (MOFU), Cierre (BOFU).",
      "Oferta ganadora: Muestra técnica gratuita de 1kg para prueba en telar.",
      "KPIs: CPL estimado < $2.10 USD con tasa de conversión a orden de compra del 38%.",
    ],
  },
  {
    id: "cierre",
    n: 24,
    kind: "cierre",
    title: "Conclusión y Cierre Comercial B2B",
    section: "social",
    speaker: 2,
    speakerName: "Orador 2 (CM & Marketing)",
    timeRange: "9:50 - 10:00",
    keyPoints: [
      "Resumen ejecutivo: Identidad visual sólida + Estrategia de contenidos integral.",
      "ALPACLADD posicionada como el eslabón de máxima confianza para marcas textiles.",
      "Llamado a la acción: Pedido de muestra técnica y apertura para preguntas de la docente.",
    ],
  },
];
